/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kwaak3_KwaakJNI */

#ifndef _Included_org_kwaak3_KwaakJNI
#define _Included_org_kwaak3_KwaakJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kwaak3_KwaakJNI
 * Method:    initGame
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_kwaak3_KwaakJNI_initGame
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_kwaak3_KwaakJNI
 * Method:    setLibraryDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kwaak3_KwaakJNI_setLibraryDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_kwaak3_KwaakJNI
 * Method:    drawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kwaak3_KwaakJNI_drawFrame
  (JNIEnv *, jclass);

/*
 * Class:     org_kwaak3_KwaakJNI
 * Method:    queueKeyEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_kwaak3_KwaakJNI_queueKeyEvent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_kwaak3_KwaakJNI
 * Method:    queueMotionEvent
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_kwaak3_KwaakJNI_queueMotionEvent
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_kwaak3_KwaakJNI
 * Method:    queueTrackballEvent
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_kwaak3_KwaakJNI_queueTrackballEvent
  (JNIEnv *, jclass, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
